### ISSUE TITLE
NTR: Slocum G3 shallow [BODCNVS-2444]

### ISSUE THREAD

**Issue by vturpin** [nvs-vocabs/B76#1]
### Term name (PrefLabel)
Slocum G3 shallow

### Definition
Slocum G3 monted with specific pump optimized for shallow dives (0 - 200m in general).

### Sources/references
 https://www.teledynemarine.com/en-us/products/SiteAssets/Webb%20Research/Teledyne%20Webb%20Research%20G3%20Brochure%202020-FINAL.pdf

### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
[Enter your ORCID if desired]

**Comment by danibodc** [comment]
Hi @vturpin just wondered if is there any urgency for this? Many thanks.

**Comment by danibodc** [comment]
Hi @vturpin this term has now been loaded and will be live on the NVS from tomorrow morning.

B7600033	Teledyne Webb Research Slocum G3 shallow glider

**Comment by vturpin** [comment]
Great thanks. I can close this issue.
